name: eventify
description: A bilingual event planning app for iOS and Android.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  http: ^1.1.0
  intl: 0.20.2
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  image_picker: ^1.0.2
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.4.0
  url_launcher: ^6.1.12
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.2.5
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  google_fonts: ^5.1.0
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  flutter_stripe: ^9.3.0
  pay: ^1.1.1
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    
  # Removed custom font declarations to use Google Fonts package instead
