// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDswg9IivAR9IWhF6RVNzoqjjux3gUV3D0',
    appId: '1:2774911262:android:8ffbf82e446dc9365a210f',
    messagingSenderId: '2774911262',
    projectId: 'eventify-e47ce',
    storageBucket: 'eventify-e47ce.firebasestorage.app',
  );

  // Configuration for Android

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr8EI7AMeorHUZGK_eIWtixidpE20dstM',
    appId: '1:2774911262:ios:df2afa28de63edb75a210f',
    messagingSenderId: '2774911262',
    projectId: 'eventify-e47ce',
    storageBucket: 'eventify-e47ce.firebasestorage.app',
    iosBundleId: 'com.eventify.eventify',
  );

  // Configuration for iOS

  // Configuration for Web
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEMOKEY123456789EXAMPLE_WEB',
    appId: '1:123456789012:web:1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'eventify-app-demo',
    storageBucket: 'eventify-app-demo.appspot.com',
    authDomain: 'eventify-app-demo.firebaseapp.com',
  );
}